import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { validateVerification } from '../src/lib/verification.ts';

test('creator applications require 10,000 followers on a single supported account', () => {
 const valid={adult:'yes',accurate:'yes',summary:'I work in cafes and can supply dated placement photographs.',profileUrl:'https://www.instagram.com/creator/',platform:'instagram',portraitUrl:'https://example.com/me.jpg',followers:'10000',accountAge:'yes',recentPosts:'yes'};
 assert.equal(validateVerification('creator',valid),null);
 assert.match(validateVerification('creator',{...valid,followers:'9999'}),/10,000/);
 assert.match(validateVerification('creator',{...valid,profileUrl:'https://instagram.com.evil.com/creator'}),/profile/);
 assert.match(validateVerification('creator',{...valid,profileUrl:'https://www.instagram.com/p/stolenpost'}),/profile/);
 assert.match(validateVerification('creator',{...valid,portraitUrl:'https://user:secret@example.com/me'}),/portrait/);
 assert.match(validateVerification('creator',{...valid,recentPosts:''}),/original posts/);
});

test('verification privacy, self-approval prevention, review audit, and marketplace gates', async t => {
 const db=new PGlite();t.after(()=>db.close());
 await db.exec(`create role anon; create role authenticated; create schema auth;
 create table auth.users(id uuid primary key,raw_user_meta_data jsonb,email_confirmed_at timestamptz);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema public,auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated;`);
 await db.exec(await readFile(new URL('../supabase/migrations/202609190001_marketplace.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../supabase/migrations/20260920111343_creator_brand_verification.sql',import.meta.url),'utf8'));
 const creator='00000000-0000-4000-8000-000000000001',brand='00000000-0000-4000-8000-000000000002',reviewer='00000000-0000-4000-8000-000000000003';
 for(const [id,role] of [[creator,'creator'],[brand,'brand'],[reviewer,'brand']]) await db.query('insert into auth.users values($1,$2,now())',[id,JSON.stringify({name:role,role})]);
 await db.query('insert into private.marketplace_reviewers values($1)',[reviewer]);
 const as=async(id,role='authenticated')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id||'']);await db.exec(`set role ${role}`);};
 const details=JSON.stringify({item:'Laptop',surface:'Lid',dimensions:'10cm',photoUrl:'https://example.com/photo.jpg',itinerary:'Cafe',visibility:'2 hours',proof:'Photo',production:'Brand ships',exclusivity:'One logo'});
 const listing=()=>db.query(`insert into placements(creator_id,creator_name,title,category,handle,audience,followers,city,country,start_date,end_date,asking_price_minor,details) values($1,'creator','Cafe laptop','Laptops','@creator','Builders',0,'Lahore','Pakistan',current_date+1,current_date+7,10000,$2) returning id`,[creator,details]);
 await as(creator);
 await assert.rejects(listing(),/row-level security/);
 await db.query("insert into verification_applications(user_id,role) values($1,'creator')",[creator]);
 await assert.rejects(db.query("update verification_applications set status='approved'"),/row-level security/);
 await assert.rejects(db.query("update verification_applications set ownership_code='fake'"),/permission denied/);
 await assert.rejects(db.query("update verification_applications set review_note='approved myself'"),/permission denied/);
 await assert.rejects(db.query("update verification_applications set status='pending'"),/check constraint/);
 const payload={adult:'yes',accurate:'yes',summary:'I work in cafes and supply placement photos.',profileUrl:'https://instagram.com/creator',platform:'instagram',portraitUrl:'https://example.com/me.jpg',accountAge:'yes',recentPosts:'yes',followers:'10000'};
 await assert.rejects(db.query("update verification_applications set payload=$1,status='pending'",[JSON.stringify({...payload,followers:'9999'})]),/check constraint/);
 await db.query("update verification_applications set payload=$1,status='pending'",[JSON.stringify(payload)]);
 assert.equal((await db.query("update verification_applications set status='draft' returning user_id")).rows.length,0);
 await assert.rejects(db.query("select review_verification($1,'approved','Self approval attempt')",[creator]),/Reviewer access/);
 await as(brand);
 assert.equal((await db.query('select * from verification_applications')).rows.length,0);
 await db.query("insert into verification_applications(user_id,role) values($1,'brand')",[brand]);
 await db.query("update verification_applications set payload=$1,status='pending'",[JSON.stringify({...payload,businessName:'Brand',authority:'yes'})]);
 await as(null,'anon');
 await assert.rejects(db.query('select * from verification_applications'),/permission denied/);
 assert.equal((await db.query('select * from placements')).rows.length,0);
 await as(reviewer);
 assert.equal((await db.query('select * from verification_applications')).rows.length,2);
 await db.query("select review_verification($1,'needs_changes','Please correct the social profile link')",[creator]);
 await as(creator);
 await db.query("update verification_applications set payload=$1,status='pending'",[JSON.stringify(payload)]);
 await as(reviewer);
 await db.query("select review_verification($1,'approved','Ownership and activity confirmed on public profile')",[creator]);
 await as(creator);
 const placement=(await listing()).rows[0].id;
 await as(brand);
 await assert.rejects(db.query('select submit_offer($1,10000,$2)',[placement,'Please place our logo on your laptop']),/marketplace approval/);
 await as(reviewer);
 await db.query("select review_verification($1,'approved','Business ownership and campaign checked')",[brand]);
 await as(brand);
 await db.query('select submit_offer($1,10000,$2)',[placement,'Please place our logo on your laptop']);
 await db.exec('reset role');
 assert.equal((await db.query('select * from private.verification_reviews')).rows.length,3);
});
