import Link from "next/link";
import { Header } from "@/components/header";
export const dynamic = "force-dynamic";
export default function Trust() {
 return <><Header /><main className="verification-page shell"><div className="eyebrow"><span /> Built on clear expectations</div><h1>Real people.<br />Brands they choose.</h1><p className="verification-lede">Before anyone publishes a placement or sends an offer, we review who they are and what they want to do.</p>
 <div className="trust-columns"><section className="verification-panel"><span className="eyebrow">For creators</span><h2>An audience of at least 10,000.</h2><p>You need at least 10,000 followers on a single Instagram, TikTok, or X account, plus an active profile and a credible real-world placement. These are Momento’s launch criteria, not social platform rules.</p><ul><li>You are 18 or older.</li><li>You control a public Instagram, TikTok, or X account with at least 90 days of history.</li><li>You have at least 3 original posts in the past 60 days.</li><li>Your profile, portrait, activity, and proposed placement tell a consistent story.</li><li>You can supply original photos of your item and dated placement proof.</li></ul><p><strong>One platform must meet the threshold.</strong> We don’t add follower counts across platforms. Reviewers check the live count, activity, authentic engagement, location, and reliability. A large following does not guarantee admission or offline reach.</p><Link href="/login?mode=signup&role=creator" className="underlined-link">Apply as a creator →</Link></section>
 <section className="verification-panel"><span className="eyebrow">For brands</span><h2>A real business. A clear brief.</h2><ul><li>You are 18 or older and authorized to represent the business.</li><li>You control its website or established public business social page.</li><li>Your business name, product, and contact presence are consistent.</li><li>You describe the product, proposed artwork, target audience, and budget.</li><li>You have the rights to use the proposed logo and advertising materials.</li></ul><p>Small businesses can use a business social page instead of a website. We may request clarification before approval. At launch, we decline illegal products, deceptive claims, adult content, gambling, tobacco, weapons, and political campaigns.</p><Link href="/login?mode=signup&role=brand" className="underlined-link">Apply as a brand →</Link></section></div>
 <section className="verification-panel"><h2>What each check actually means</h2><div className="trust-columns"><div><h3>Email confirmed</h3><p>You control the email used to sign in. This does not verify a social account or business.</p></div><div><h3>Marketplace approved</h3><p>A reviewer checked the ownership code on your public page and reviewed your application against the criteria above. This is not a guarantee of performance.</p></div></div><h3>How ownership is checked</h3><p>We generate a unique code for your account. Add it to your public social bio or business website, then submit the link. A reviewer checks the live page. A screenshot alone is not enough. Keep the code visible until you receive a decision; you can remove it afterward.</p><p>We do not currently connect to social APIs or automatically verify follower counts. Profile follower numbers are self-reported and are never presented as guaranteed impressions.</p><h3>Payment identity is separate</h3><p>Payment-provider checks and payout eligibility are separate from marketplace admission. Payment collection and payouts are not enabled in this preview.</p><h3>If your application needs changes</h3><p>You’ll see a specific reason in your dashboard. Update your details and resubmit for another review. We never approve an account just because a form was completed.</p><Link className="button button-primary" href="/verify">Open my application</Link></section>
 </main></>;
}
