import Link from "next/link";
import { Header } from "@/components/header";
export const dynamic = "force-dynamic";
export default function Trust() {
 return <><Header /><main className="verification-page shell"><div className="eyebrow"><span /> Built on clear expectations</div><h1>Real people.<br />Verified in about a minute.</h1><p className="verification-lede">Before anyone publishes a placement or sends an offer, we confirm they control the profile or website they claim — automatically, against the live public page. Here’s exactly what that means.</p>
 <div className="trust-columns"><section className="verification-panel"><span className="eyebrow">For creators</span><h2>Any real, public creator account.</h2><p>There’s no follower minimum. You need a public Instagram, TikTok, or X account that you control, and a realistic real-world placement plan.</p><ul><li>You are 18 or older.</li><li>You control a public Instagram, TikTok, or X profile.</li><li>You add your one-time Momento code to that bio so our automatic check can see it live.</li><li>Your name, photo, and audience size are read straight from your public page — never self-reported.</li><li>You can supply original photos of your item and dated placement proof.</li></ul><p><strong>Audience size is shown, not gated.</strong> Brands see the follower count read from your live profile and decide for themselves. A large following is never presented as guaranteed offline reach.</p><Link href="/login?mode=signup&role=creator" className="underlined-link">Join as a creator →</Link></section>
 <section className="verification-panel"><span className="eyebrow">For brands</span><h2>A real business. A clear brief.</h2><ul><li>You are 18 or older and authorized to represent the business.</li><li>You control its website or an established public business social page.</li><li>You place your one-time Momento code on that page so our automatic check can confirm it.</li><li>You describe what you sell and what you’d like to advertise.</li><li>You have the rights to the logo and advertising materials you propose.</li></ul><p>Small businesses can use a business social page instead of a website. At launch, we decline illegal products, deceptive claims, adult content, gambling, tobacco, weapons, and political campaigns.</p><Link href="/login?mode=signup&role=brand" className="underlined-link">Join as a brand →</Link></section></div>
 <section className="verification-panel"><h2>How the automatic check works</h2><p>We generate a unique code for your account. You add it to your public bio or website, paste your link, and press Verify. Our system reads the live page, confirms the code is visible, and picks up your public name, photo, and follower count. Most decisions land in under a minute, and you can remove the code as soon as you’re approved.</p><div className="trust-columns"><div><h3>Email confirmed</h3><p>You control the email used to sign in. This does not verify a social account or business.</p></div><div><h3>Marketplace verified</h3><p>Our automatic check saw your code live on the page you linked. This proves control of that page — it is not a guarantee of performance or impressions.</p></div></div><h3>If the check can’t reach your page</h3><p>You’ll see exactly what went wrong straight away — a private profile, a missing code, or a page that wouldn’t load — and you can fix it and verify again immediately. Nothing sits in a queue. Human reviewers only step in on environments where automatic checks are switched off, or if a decision is ever disputed.</p><h3>Payment identity is separate</h3><p>Payment-provider checks and payout eligibility are separate from marketplace verification. Payment collection and payouts are not enabled in this preview.</p><h3>What we never ask for</h3><p>No passwords, no ID documents, no home addresses, no payment details. We only read the public page you link — the same page anyone on the internet can see.</p><Link className="button button-primary" href="/verify">Verify my account</Link></section>
 </main></>;
}
