import { notFound, redirect } from "next/navigation";
import { Header } from "@/components/header";
import { currentAccount } from "@/lib/supabase/server";
import { safePublicUrl } from "@/lib/verification";
import { reviewApplication } from "./actions";
export const dynamic = "force-dynamic";
export default async function Review({ searchParams }: { searchParams: Promise<{ message?: string }> }) {
 const account = await currentAccount(); if (!account) redirect("/login");
 const {data: reviewer} = await account.client.rpc("is_marketplace_reviewer"); if (!reviewer) notFound();
 const {data: applications,error} = await account.client.from("verification_applications").select("*").eq("status","pending").order("created_at");
 const {message} = await searchParams;
 return <><Header /><main className="verification-page shell"><h1>Member reviews</h1><p>Check the live ownership code, recent activity, and the criteria on the trust page. Record a reason for every decision.</p>{message && <p role="status">{message}</p>}{error && <p role="alert">Could not load the queue.</p>}{!error && !applications?.length && <p>No applications awaiting review.</p>}{applications?.map(a => <article className="verification-panel" key={a.user_id}><h2>{a.role === "creator" ? "Creator" : a.payload.businessName || "Brand"} application</h2><p>Ownership code: <code>{a.ownership_code}</code></p>{safePublicUrl(a.payload.profileUrl) && <a className="underlined-link" href={a.payload.profileUrl} target="_blank" rel="noopener noreferrer">Open public profile / website ↗</a>}<p>{a.payload.summary}</p><p>{a.payload.platform} · {a.payload.followers ? `${a.payload.followers} followers (self-reported)` : "Business applicant"}</p>{safePublicUrl(a.payload.portraitUrl) && <a className="underlined-link" href={a.payload.portraitUrl} target="_blank" rel="noopener noreferrer">Check portrait ↗</a>}<form action={reviewApplication} className="verification-form"><input type="hidden" name="applicant" value={a.user_id} /><label className="check-label"><input type="checkbox" name="ownership" value="yes" /> I saw this exact ownership code on the live public page.</label><label className="check-label"><input type="checkbox" name="eligibility" value="yes" /> I checked age declaration and the role-specific admission criteria (creators: at least 10,000 followers on this single account, 90 days of history, and 3 recent original posts).</label><label className="check-label"><input type="checkbox" name="fit" value="yes" /> I checked consistency, authentic activity, and campaign suitability.</label><label>Decision note (visible to applicant)<textarea name="note" required minLength={10} maxLength={1500} rows={3} /></label><div className="hero-actions"><button className="button button-primary" name="decision" value="approved">Approve member</button><button className="button button-outline" name="decision" value="needs_changes">Request changes</button></div></form></article>)}</main></>;
}
